// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (9090);

service /v1 on ep0 {
    # Get Multiple Catalog Albums
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + ids - The unique identifiers for the albums
    # + extend - A list of attribute extensions to apply to resources in the response
    # + filter - A filter to apply to the request
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + restrict - A set of restrictions (for example, to restrict explicit content)
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/albums(string[]? ids, string[]? extend, string[]? filter, string[]? include, string? l, string[]? restrict) returns AlbumsResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "1440857781",
                    "type": "albums",
                    "href": "/v1/catalog/us/albums/1440857781",
                    "attributes": {
                        "name": "Abbey Road",
                        "artistName": "The Beatles",
                        "genreNames": ["Rock", "Pop"],
                        "releaseDate": "1969-09-26",
                        "trackCount": 17,
                        "isCompilation": false,
                        "isSingle": false,
                        "isComplete": true,
                        "isMasteredForItunes": true,
                        "artwork": {
                            "width": 1400,
                            "height": 1400,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/7b/4b/f4/7b4bf4c5-7b8d-8d0f-8d8f-8d8f8d8f8d8f/{w}x{h}bb.jpg"
                        },
                        "playParams": {
                            "id": "1440857781",
                            "kind": "album"
                        },
                        "url": "https://music.apple.com/us/album/abbey-road/1440857781"
                    }
                }
            ]
        };
    }

    # Get a Catalog Album
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + id - The unique identifier for the album
    # + views - The views to activate for the albums resource
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/albums/[string id](("appears-on"|"other-versions"|"related-albums"|"related-videos")[]? views, string[]? extend, string[]? include, string? l) returns AlbumsResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": id,
                    "type": "albums",
                    "href": "/v1/catalog/" + storefront + "/albums/" + id,
                    "attributes": {
                        "name": "Thriller",
                        "artistName": "Michael Jackson",
                        "genreNames": ["Pop", "R&B/Soul"],
                        "releaseDate": "1982-11-30",
                        "trackCount": 9,
                        "isCompilation": false,
                        "isSingle": false,
                        "isComplete": true,
                        "isMasteredForItunes": true,
                        "artwork": {
                            "width": 1400,
                            "height": 1400,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/thriller/{w}x{h}bb.jpg"
                        },
                        "playParams": {
                            "id": id,
                            "kind": "album"
                        },
                        "url": "https://music.apple.com/us/album/thriller/" + id
                    }
                }
            ]
        };
    }

    # Get a Catalog Album's Relationship Directly by Name
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + id - The unique identifier for the album
    # + relationship - The name of the relationship you want to fetch for this resource
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/albums/[string id]/["artists"|"genres"|"library"|"record-labels"|"tracks" relationship](string[]? extend, string[]? include, string? l, int 'limit = 5) returns ArtistsResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "136975",
                    "type": "artists",
                    "href": "/v1/catalog/" + storefront + "/artists/136975",
                    "attributes": {
                        "name": "The Beatles",
                        "genreNames": ["Rock", "Pop"],
                        "url": "https://music.apple.com/us/artist/the-beatles/136975"
                    }
                }
            ]
        };
    }

    # Get a Catalog Album's Relationship View Directly by Name
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + id - The unique identifier for the album
    # + view - The name of the resource view to fetch
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + with - A list of modifications to apply to the request
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/albums/[string id]/view/["appears-on"|"other-versions"|"related-albums"|"related-videos" view](string[]? extend, string[]? include, string? l, ("attributes"|"topResults")[]? with, int 'limit = 5) returns MusicVideosResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "1234567890",
                    "type": "music-videos",
                    "href": "/v1/catalog/" + storefront + "/music-videos/1234567890",
                    "attributes": {
                        "name": "Hey Jude",
                        "artistName": "The Beatles",
                        "genreNames": ["Rock", "Pop"],
                        "durationInMillis": 431000,
                        "releaseDate": "1968-08-26",
                        "has4K": true,
                        "hasHDR": false,
                        "artwork": {
                            "width": 1920,
                            "height": 1080,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Video125/v4/hey-jude/{w}x{h}bb.jpg"
                        },
                        "playParams": {
                            "id": "1234567890",
                            "kind": "musicVideo"
                        },
                        "url": "https://music.apple.com/us/music-video/hey-jude/1234567890",
                        "previews": [
                            {
                                "url": "https://video-ssl.itunes.apple.com/itunes-assets/Video128/v4/hey-jude-preview.m4v"
                            }
                        ]
                    }
                }
            ]
        };
    }

    # Get Multiple Catalog Artists
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + ids - The unique identifiers for the artists
    # + extend - A list of attribute extensions to apply to resources in the response
    # + filter - A filter to apply to the request
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + restrict - A set of restrictions (for example, to restrict explicit content)
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/artists(string[]? ids, string[]? extend, string[]? filter, string[]? include, string? l, string[]? restrict) returns ArtistsResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "136975",
                    "type": "artists",
                    "href": "/v1/catalog/" + storefront + "/artists/136975",
                    "attributes": {
                        "name": "The Beatles",
                        "genreNames": ["Rock", "Pop"],
                        "url": "https://music.apple.com/us/artist/the-beatles/136975"
                    }
                },
                {
                    "id": "32940",
                    "type": "artists",
                    "href": "/v1/catalog/" + storefront + "/artists/32940",
                    "attributes": {
                        "name": "Michael Jackson",
                        "genreNames": ["Pop", "R&B/Soul"],
                        "url": "https://music.apple.com/us/artist/michael-jackson/32940"
                    }
                }
            ]
        };
    }

    # Get a Catalog Artist
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + id - The unique identifier for the artist
    # + views - The views to activate for the artists resource
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/artists/[string id](("appears-on-albums"|"compilation-albums"|"featured-albums"|"featured-playlists"|"full-albums"|"latest-release"|"live-albums"|"similar-artists"|"singles"|"top-music-videos"|"top-songs")[]? views, string[]? extend, string[]? include, string? l) returns ArtistsResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": id,
                    "type": "artists",
                    "href": "/v1/catalog/" + storefront + "/artists/" + id,
                    "attributes": {
                        "name": "Taylor Swift",
                        "genreNames": ["Pop", "Country"],
                        "url": "https://music.apple.com/us/artist/taylor-swift/" + id
                    }
                }
            ]
        };
    }

    # Get a Catalog Artist's Relationship Directly by Name
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + id - The unique identifier for the artist
    # + relationship - The name of the relationship you want to fetch for this resource
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/artists/[string id]/["albums"|"genres"|"music-videos"|"playlists"|"station" relationship](string[]? extend, string[]? include, string? l, int 'limit = 5) returns AlbumsResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "1440857781",
                    "type": "albums",
                    "href": "/v1/catalog/" + storefront + "/albums/1440857781",
                    "attributes": {
                        "name": "1989 (Taylor's Version)",
                        "artistName": "Taylor Swift",
                        "genreNames": ["Pop"],
                        "releaseDate": "2023-10-27",
                        "trackCount": 21,
                        "isCompilation": false,
                        "isSingle": false,
                        "isComplete": true,
                        "isMasteredForItunes": true,
                        "artwork": {
                            "width": 1400,
                            "height": 1400,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/1989-tv/{w}x{h}bb.jpg"
                        },
                        "playParams": {
                            "id": "1440857781",
                            "kind": "album"
                        },
                        "url": "https://music.apple.com/us/album/1989-taylors-version/1440857781"
                    }
                }
            ]
        };
    }

    # Get a Catalog Artist's Relationship View Directly by Name
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + id - The unique identifier for the artist
    # + view - The name of the resource view to fetch
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + with - A list of modifications to apply to the request
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/artists/[string id]/view/["appears-on-albums"|"compilation-albums"|"featured-albums"|"featured-playlists"|"full-albums"|"latest-release"|"live-albums"|"similar-artists"|"singles"|"top-music-videos"|"top-songs" view](string[]? extend, string[]? include, string? l, ("attributes"|"topResults")[]? with, int 'limit = 5) returns AlbumsResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "1708283165",
                    "type": "albums",
                    "href": "/v1/catalog/" + storefront + "/albums/1708283165",
                    "attributes": {
                        "name": "The Tortured Poets Department",
                        "artistName": "Taylor Swift",
                        "genreNames": ["Pop", "Alternative"],
                        "releaseDate": "2024-04-19",
                        "trackCount": 16,
                        "isCompilation": false,
                        "isSingle": false,
                        "isComplete": true,
                        "isMasteredForItunes": true,
                        "artwork": {
                            "width": 1400,
                            "height": 1400,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/tortured-poets/{w}x{h}bb.jpg"
                        },
                        "playParams": {
                            "id": "1708283165",
                            "kind": "album"
                        },
                        "url": "https://music.apple.com/us/album/the-tortured-poets-department/1708283165"
                    }
                }
            ]
        };
    }

    # Search for Catalog Resources
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + offset - The next page or group of objects to fetch
    # + term - The entered text for the search with `+` characters between each word, to replace spaces (for example `term=james+br`)
    # + types - The list of the types of resources to include in the results
    # + with - A list of modifications to apply to the request
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/search(string? l, string? offset, string term, ("activities"|"albums"|"apple-curators"|"artists"|"curators"|"music-videos"|"playlists"|"record-labels"|"songs"|"stations")[]? types, ("attributes"|"topResults")[]? with, int 'limit = 5) returns SearchResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "results": {
                "albums": {
                    "data": [
                        {
                            "id": "1440857781",
                            "type": "albums",
                            "href": "/v1/catalog/" + storefront + "/albums/1440857781",
                            "attributes": {
                                "name": "Abbey Road",
                                "artistName": "The Beatles",
                                "genreNames": ["Rock", "Pop"],
                                "releaseDate": "1969-09-26",
                                "trackCount": 17,
                                "isCompilation": false,
                                "isSingle": false,
                                "isComplete": true,
                                "isMasteredForItunes": true,
                                "artwork": {
                                    "width": 1400,
                                    "height": 1400,
                                    "url": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/abbey-road/{w}x{h}bb.jpg"
                                },
                                "playParams": {
                                    "id": "1440857781",
                                    "kind": "album"
                                },
                                "url": "https://music.apple.com/us/album/abbey-road/1440857781"
                            }
                        }
                    ]
                },
                "artists": {
                    "data": [
                        {
                            "id": "136975",
                            "type": "artists",
                            "href": "/v1/catalog/" + storefront + "/artists/136975",
                            "attributes": {
                                "name": "The Beatles",
                                "genreNames": ["Rock", "Pop"],
                                "url": "https://music.apple.com/us/artist/the-beatles/136975"
                            }
                        }
                    ]
                }
            }
        };
    }

    # Get Multiple Catalog Songs by ID
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + ids - The unique identifiers for the songs
    # + extend - A list of attribute extensions to apply to resources in the response
    # + filter - A filter to apply to the request
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + restrict - A set of restrictions (for example, to restrict explicit content)
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/songs(string[]? ids, string[]? extend, string[]? filter, string[]? include, string? l, string[]? restrict) returns SongsResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "1440857781",
                    "type": "songs",
                    "href": "/v1/catalog/" + storefront + "/songs/1440857781",
                    "attributes": {
                        "name": "Come Together",
                        "artistName": "The Beatles",
                        "albumName": "Abbey Road",
                        "genreNames": ["Rock", "Pop"],
                        "durationInMillis": 259000,
                        "releaseDate": "1969-09-26",
                        "trackNumber": 1,
                        "discNumber": 1,
                        "hasLyrics": true,
                        "artwork": {
                            "width": 1400,
                            "height": 1400,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/come-together/{w}x{h}bb.jpg"
                        },
                        "playParams": {
                            "id": "1440857781",
                            "kind": "song"
                        },
                        "url": "https://music.apple.com/us/album/abbey-road/1440857781?i=1440857781",
                        "previews": [
                            {
                                "url": "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/come-together-preview.m4a"
                            }
                        ]
                    }
                }
            ]
        };
    }

    # Get a Catalog Song
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + id - The unique identifier for the song
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/songs/[string id](string[]? extend, string[]? include, string? l) returns SongsResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": id,
                    "type": "songs",
                    "href": "/v1/catalog/" + storefront + "/songs/" + id,
                    "attributes": {
                        "name": "Shake It Off",
                        "artistName": "Taylor Swift",
                        "albumName": "1989 (Taylor's Version)",
                        "genreNames": ["Pop"],
                        "durationInMillis": 219000,
                        "releaseDate": "2023-10-27",
                        "trackNumber": 6,
                        "discNumber": 1,
                        "hasLyrics": true,
                        "artwork": {
                            "width": 1400,
                            "height": 1400,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/shake-it-off/{w}x{h}bb.jpg"
                        },
                        "playParams": {
                            "id": id,
                            "kind": "song"
                        },
                        "url": "https://music.apple.com/us/album/1989-taylors-version/1708283165?i=" + id,
                        "previews": [
                            {
                                "url": "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/shake-it-off-preview.m4a"
                            }
                        ]
                    }
                }
            ]
        };
    }

    # Get a Catalog Song's Relationship Directly by Name
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + id - The unique identifier for the song
    # + relationship - The name of the relationship you want to fetch for this resource
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/songs/[string id]/["albums"|"artists"|"composers"|"genres"|"library"|"music-videos"|"station" relationship](string[]? extend, string[]? include, string? l, int 'limit = 5) returns SongsResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "1708283165",
                    "type": "songs",
                    "href": "/v1/catalog/" + storefront + "/songs/1708283165",
                    "attributes": {
                        "name": "Anti-Hero",
                        "artistName": "Taylor Swift",
                        "albumName": "Midnights",
                        "genreNames": ["Pop", "Alternative"],
                        "durationInMillis": 200000,
                        "releaseDate": "2022-10-21",
                        "trackNumber": 3,
                        "discNumber": 1,
                        "hasLyrics": true,
                        "artwork": {
                            "width": 1400,
                            "height": 1400,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/anti-hero/{w}x{h}bb.jpg"
                        },
                        "playParams": {
                            "id": "1708283165",
                            "kind": "song"
                        },
                        "url": "https://music.apple.com/us/album/midnights/1645817813?i=1708283165",
                        "previews": [
                            {
                                "url": "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/anti-hero-preview.m4a"
                            }
                        ]
                    }
                }
            ]
        };
    }

    # Get All Library Albums
    #
    # + ids - The unique identifiers for the albums
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + offset - The next page or group of objects to fetch
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:Forbidden (Forbidden)
    # http:InternalServerError (Internal Server Error)
    resource function get me/library/albums(string[]? ids, string[]? extend, string[]? include, string? l, string? offset, int 'limit = 5) returns LibraryAlbumsResponse|ErrorsResponseUnauthorized|ErrorsResponseForbidden|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "l.abc123",
                    "type": "library-albums",
                    "href": "/v1/me/library/albums/l.abc123",
                    "attributes": {
                        "name": "Folklore",
                        "artistName": "Taylor Swift",
                        "genreNames": ["Alternative", "Indie Folk"],
                        "releaseDate": "2020-07-24",
                        "trackCount": 16,
                        "dateAdded": "2020-07-24",
                        "artwork": {
                            "width": 1400,
                            "height": 1400,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/folklore/{w}x{h}bb.jpg"
                        },
                        "playParams": {
                            "id": "l.abc123",
                            "kind": "album"
                        }
                    }
                }
            ]
        };
    }

    # Get a Library Album
    #
    # + id - The unique identifier for the album
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:Forbidden (Forbidden)
    # http:InternalServerError (Internal Server Error)
    resource function get me/library/albums/[string id](string[]? extend, string[]? include, string? l) returns LibraryAlbumsResponse|ErrorsResponseUnauthorized|ErrorsResponseForbidden|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": id,
                    "type": "library-albums",
                    "href": "/v1/me/library/albums/" + id,
                    "attributes": {
                        "name": "Evermore",
                        "artistName": "Taylor Swift",
                        "genreNames": ["Alternative", "Indie Folk"],
                        "releaseDate": "2020-12-11",
                        "trackCount": 15,
                        "dateAdded": "2020-12-11",
                        "artwork": {
                            "width": 1400,
                            "height": 1400,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/evermore/{w}x{h}bb.jpg"
                        },
                        "playParams": {
                            "id": id,
                            "kind": "album"
                        }
                    }
                }
            ]
        };
    }

    # Get a Library Album's Relationship Directly by Name
    #
    # + id - The unique identifier for the album
    # + relationship - The name of the relationship you want to fetch for this resource
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:Forbidden (Forbidden)
    # http:InternalServerError (Internal Server Error)
    resource function get me/library/albums/[string id]/["artists"|"genres"|"library"|"record-labels"|"tracks" relationship](string[]? extend, string[]? include, string? l, int 'limit = 5) returns LibraryArtistsResponse|ErrorsResponseUnauthorized|ErrorsResponseForbidden|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "l.artist456",
                    "type": "library-artists",
                    "href": "/v1/me/library/artists/l.artist456",
                    "attributes": {
                        "name": "Taylor Swift"
                    }
                }
            ]
        };
    }

    # Get All Library Artists
    #
    # + ids - The unique identifiers for the artists
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + offset - The next page or group of objects to fetch
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:Forbidden (Forbidden)
    # http:InternalServerError (Internal Server Error)
    resource function get me/library/artists(string[]? ids, string[]? extend, string[]? include, string? l, string? offset, int 'limit = 5) returns LibraryArtistsResponse|ErrorsResponseUnauthorized|ErrorsResponseForbidden|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "l.artist123",
                    "type": "library-artists",
                    "href": "/v1/me/library/artists/l.artist123",
                    "attributes": {
                        "name": "The Beatles"
                    }
                },
                {
                    "id": "l.artist456",
                    "type": "library-artists",
                    "href": "/v1/me/library/artists/l.artist456",
                    "attributes": {
                        "name": "Taylor Swift"
                    }
                }
            ]
        };
    }

    # Get a Library Artist
    #
    # + id - The unique identifier for the artist
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:Forbidden (Forbidden)
    # http:InternalServerError (Internal Server Error)
    resource function get me/library/artists/[string id](string[]? extend, string[]? include, string? l) returns LibraryArtistsResponse|ErrorsResponseUnauthorized|ErrorsResponseForbidden|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": id,
                    "type": "library-artists",
                    "href": "/v1/me/library/artists/" + id,
                    "attributes": {
                        "name": "Ed Sheeran"
                    }
                }
            ]
        };
    }

    # Get a Library Artist's Relationship Directly by Name
    #
    # + id - The unique identifier for the artist
    # + relationship - The name of the relationship you want to fetch for this resource
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:Forbidden (Forbidden)
    # http:InternalServerError (Internal Server Error)
    resource function get me/library/artists/[string id]/["albums"|"genres"|"music-videos"|"playlists"|"station" relationship](string[]? extend, string[]? include, string? l, int 'limit = 5) returns LibraryAlbumsResponse|ErrorsResponseUnauthorized|ErrorsResponseForbidden|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "l.album789",
                    "type": "library-albums",
                    "href": "/v1/me/library/albums/l.album789",
                    "attributes": {
                        "name": "÷ (Divide)",
                        "artistName": "Ed Sheeran",
                        "genreNames": ["Pop", "Singer/Songwriter"],
                        "releaseDate": "2017-03-03",
                        "trackCount": 12,
                        "dateAdded": "2017-03-10",
                        "artwork": {
                            "width": 1400,
                            "height": 1400,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/divide/{w}x{h}bb.jpg"
                        },
                        "playParams": {
                            "id": "l.album789",
                            "kind": "album"
                        }
                    }
                }
            ]
        };
    }

    # Get All Library Songs
    #
    # + ids - The unique identifiers for the songs
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + offset - The next page or group of objects to fetch
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:Forbidden (Forbidden)
    # http:InternalServerError (Internal Server Error)
    resource function get me/library/songs(string[]? ids, string[]? extend, string[]? include, string? l, string? offset, int 'limit = 5) returns LibrarySongsResponse|ErrorsResponseUnauthorized|ErrorsResponseForbidden|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "l.song123",
                    "type": "library-songs",
                    "href": "/v1/me/library/songs/l.song123",
                    "attributes": {
                        "name": "Cardigan",
                        "artistName": "Taylor Swift",
                        "albumName": "Folklore",
                        "genreNames": ["Alternative", "Indie Folk"],
                        "durationInMillis": 239000,
                        "releaseDate": "2020-07-24",
                        "trackNumber": 2,
                        "discNumber": 1,
                        "hasLyrics": true,
                        "artwork": {
                            "width": 1400,
                            "height": 1400,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/cardigan/{w}x{h}bb.jpg"
                        },
                        "playParams": {
                            "id": "l.song123",
                            "kind": "song"
                        }
                    }
                }
            ]
        };
    }

    # Get a Library Song
    #
    # + id - The unique identifier for the song
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:Forbidden (Forbidden)
    # http:InternalServerError (Internal Server Error)
    resource function get me/library/songs/[string id](string[]? extend, string[]? include, string? l) returns LibrarySongsResponse|ErrorsResponseUnauthorized|ErrorsResponseForbidden|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": id,
                    "type": "library-songs",
                    "href": "/v1/me/library/songs/" + id,
                    "attributes": {
                        "name": "Willow",
                        "artistName": "Taylor Swift",
                        "albumName": "Evermore",
                        "genreNames": ["Alternative", "Country"],
                        "durationInMillis": 214000,
                        "releaseDate": "2020-12-11",
                        "trackNumber": 1,
                        "discNumber": 1,
                        "hasLyrics": true,
                        "artwork": {
                            "width": 1400,
                            "height": 1400,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/willow/{w}x{h}bb.jpg"
                        },
                        "playParams": {
                            "id": id,
                            "kind": "song"
                        }
                    }
                }
            ]
        };
    }

    # Get a Library Song's Relationship Directly by Name
    #
    # + id - The unique identifier for the song
    # + relationship - The name of the relationship you want to fetch for this resource
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:Forbidden (Forbidden)
    # http:InternalServerError (Internal Server Error)
    resource function get me/library/songs/[string id]/["albums"|"artists"|"composers"|"genres"|"library"|"music-videos"|"station" relationship](string[]? extend, string[]? include, string? l, int 'limit = 5) returns LibrarySongsResponse|ErrorsResponseUnauthorized|ErrorsResponseForbidden|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "l.relatedsong456",
                    "type": "library-songs",
                    "href": "/v1/me/library/songs/l.relatedsong456",
                    "attributes": {
                        "name": "August",
                        "artistName": "Taylor Swift",
                        "albumName": "Folklore",
                        "genreNames": ["Alternative", "Indie Folk"],
                        "durationInMillis": 261000,
                        "releaseDate": "2020-07-24",
                        "trackNumber": 8,
                        "discNumber": 1,
                        "hasLyrics": true,
                        "artwork": {
                            "width": 1400,
                            "height": 1400,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/august/{w}x{h}bb.jpg"
                        },
                        "playParams": {
                            "id": "l.relatedsong456",
                            "kind": "song"
                        }
                    }
                }
            ]
        };
    }

    # Add a Resource to a Library
    #
    # + ids - The unique catalog identifiers for the resources. To indicate the type of resource to be added, ids must be followed by one of the allowed values. Add multiple types in the same request
    # + return - returns can be any of following types 
    # http:Accepted (Accepted)
    # http:Unauthorized (Unauthorized)
    # http:Forbidden (Forbidden)
    # http:InternalServerError (Internal Server Error)
    resource function post me/library(string[] ids) returns http:Accepted|ErrorsResponseUnauthorized|ErrorsResponseForbidden|ErrorsResponseInternalServerError {
        return http:ACCEPTED;
    }
}