// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (9090);

service /v1 on ep0 {
    # Get Multiple Catalog Albums
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + ids - The unique identifiers for the albums
    # + extend - A list of attribute extensions to apply to resources in the response
    # + filter - A filter to apply to the request
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + restrict - A set of restrictions (for example, to restrict explicit content)
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/albums(string[]? ids, string[]? extend, string[]? filter, string[]? include, string? l, string[]? restrict) returns AlbumsResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "1234567890",
                    "type": "albums",
                    "href": "/v1/catalog/us/albums/1234567890",
                    "attributes": {
                        "artistName": "The Beatles",
                        "name": "Abbey Road",
                        "releaseDate": "1969-09-26",
                        "genreNames": ["Rock", "Pop"],
                        "trackCount": 17,
                        "copyright": "© 1969 Apple Records",
                        "recordLabel": "Apple Records",
                        "url": "https://music.apple.com/us/album/abbey-road/1234567890",
                        "isComplete": true,
                        "isSingle": false,
                        "isCompilation": false,
                        "isMasteredForItunes": true,
                        "upc": "094638246411",
                        "artwork": {
                            "width": 600,
                            "height": 600,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music/v4/album.jpg/{w}x{h}bb.jpeg",
                            "bgColor": "ffffff",
                            "textColor1": "000000",
                            "textColor2": "333333",
                            "textColor3": "666666",
                            "textColor4": "999999"
                        },
                        "playParams": {
                            "id": "1234567890",
                            "kind": "album"
                        },
                        "editorialNotes": {
                            "standard": "The Beatles' final recorded album, Abbey Road is a masterpiece.",
                            "short": "The Beatles' swan song masterpiece."
                        }
                    }
                }
            ]
        };
    }

    # Get a Catalog Album
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + id - The unique identifier for the album
    # + views - The views to activate for the albums resource
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/albums/[string id](("appears-on"|"other-versions"|"related-albums"|"related-videos")[]? views, string[]? extend, string[]? include, string? l) returns AlbumsResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": id,
                    "type": "albums",
                    "href": "/v1/catalog/" + storefront + "/albums/" + id,
                    "attributes": {
                        "artistName": "Taylor Swift",
                        "name": "1989 (Taylor's Version)",
                        "releaseDate": "2023-10-27",
                        "genreNames": ["Pop"],
                        "trackCount": 21,
                        "copyright": "© 2023 Taylor Swift",
                        "recordLabel": "Taylor Swift",
                        "url": "https://music.apple.com/us/album/1989-taylors-version/" + id,
                        "isComplete": true,
                        "isSingle": false,
                        "isCompilation": false,
                        "isMasteredForItunes": true,
                        "artwork": {
                            "width": 3000,
                            "height": 3000,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/album.jpg/{w}x{h}bb.jpeg",
                            "bgColor": "87ceeb",
                            "textColor1": "0f1419",
                            "textColor2": "2a2f35",
                            "textColor3": "2c3d47",
                            "textColor4": "424951"
                        },
                        "playParams": {
                            "id": id,
                            "kind": "album"
                        }
                    }
                }
            ]
        };
    }

    # Get a Catalog Album's Relationship Directly by Name
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + id - The unique identifier for the album
    # + relationship - The name of the relationship you want to fetch for this resource
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/albums/[string id]/["artists"|"genres"|"library"|"record-labels"|"tracks" relationship](string[]? extend, string[]? include, string? l, int 'limit = 5) returns ArtistsResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "159260351",
                    "type": "artists",
                    "href": "/v1/catalog/" + storefront + "/artists/159260351",
                    "attributes": {
                        "name": "Taylor Swift",
                        "genreNames": ["Pop", "Country"],
                        "url": "https://music.apple.com/us/artist/taylor-swift/159260351"
                    }
                }
            ]
        };
    }

    # Get a Catalog Album's Relationship View Directly by Name
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + id - The unique identifier for the album
    # + view - The name of the resource view to fetch
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + with - A list of modifications to apply to the request
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/albums/[string id]/view/["appears-on"|"other-versions"|"related-albums"|"related-videos" view](string[]? extend, string[]? include, string? l, ("attributes"|"topResults")[]? with, int 'limit = 5) returns MusicVideosResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "1440857781",
                    "type": "music-videos",
                    "href": "/v1/catalog/" + storefront + "/music-videos/1440857781",
                    "attributes": {
                        "albumName": "Shake It Off",
                        "artistName": "Taylor Swift",
                        "name": "Shake It Off",
                        "genreNames": ["Pop"],
                        "durationInMillis": 242000,
                        "releaseDate": "2014-08-18",
                        "url": "https://music.apple.com/us/music-video/shake-it-off/1440857781",
                        "has4K": true,
                        "hasHDR": false,
                        "artwork": {
                            "width": 1920,
                            "height": 1080,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Video/v4/mv.jpg/{w}x{h}bb.jpeg"
                        },
                        "playParams": {
                            "id": "1440857781",
                            "kind": "musicVideo"
                        },
                        "previews": [
                            {
                                "url": "https://video-ssl.itunes.apple.com/itunes-assets/Video/preview.m4v"
                            }
                        ]
                    }
                }
            ]
        };
    }

    # Get Multiple Catalog Artists
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + ids - The unique identifiers for the artists
    # + extend - A list of attribute extensions to apply to resources in the response
    # + filter - A filter to apply to the request
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + restrict - A set of restrictions (for example, to restrict explicit content)
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/artists(string[]? ids, string[]? extend, string[]? filter, string[]? include, string? l, string[]? restrict) returns ArtistsResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "159260351",
                    "type": "artists",
                    "href": "/v1/catalog/" + storefront + "/artists/159260351",
                    "attributes": {
                        "name": "Taylor Swift",
                        "genreNames": ["Pop", "Country", "Alternative"],
                        "url": "https://music.apple.com/us/artist/taylor-swift/159260351",
                        "editorialNotes": {
                            "standard": "Taylor Swift is a multi-Grammy Award-winning singer-songwriter.",
                            "short": "Multi-Grammy Award winner."
                        }
                    }
                },
                {
                    "id": "136975",
                    "type": "artists",
                    "href": "/v1/catalog/" + storefront + "/artists/136975",
                    "attributes": {
                        "name": "Ed Sheeran",
                        "genreNames": ["Pop", "Singer/Songwriter"],
                        "url": "https://music.apple.com/us/artist/ed-sheeran/136975"
                    }
                }
            ]
        };
    }

    # Get a Catalog Artist
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + id - The unique identifier for the artist
    # + views - The views to activate for the artists resource
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/artists/[string id](("appears-on-albums"|"compilation-albums"|"featured-albums"|"featured-playlists"|"full-albums"|"latest-release"|"live-albums"|"similar-artists"|"singles"|"top-music-videos"|"top-songs")[]? views, string[]? extend, string[]? include, string? l) returns ArtistsResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": id,
                    "type": "artists",
                    "href": "/v1/catalog/" + storefront + "/artists/" + id,
                    "attributes": {
                        "name": "Adele",
                        "genreNames": ["Pop", "Soul", "R&B/Soul"],
                        "url": "https://music.apple.com/us/artist/adele/" + id,
                        "editorialNotes": {
                            "standard": "Adele is one of the most successful artists of the 21st century.",
                            "short": "Powerhouse vocalist and songwriter."
                        }
                    }
                }
            ]
        };
    }

    # Get a Catalog Artist's Relationship Directly by Name
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + id - The unique identifier for the artist
    # + relationship - The name of the relationship you want to fetch for this resource
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/artists/[string id]/["albums"|"genres"|"music-videos"|"playlists"|"station" relationship](string[]? extend, string[]? include, string? l, int 'limit = 5) returns AlbumsResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "1440935467",
                    "type": "albums",
                    "href": "/v1/catalog/" + storefront + "/albums/1440935467",
                    "attributes": {
                        "artistName": "Adele",
                        "name": "30",
                        "releaseDate": "2021-11-19",
                        "genreNames": ["Pop", "Soul"],
                        "trackCount": 12,
                        "copyright": "© 2021 Melted Stone Ltd.",
                        "recordLabel": "Columbia Records",
                        "url": "https://music.apple.com/us/album/30/1440935467",
                        "isComplete": true,
                        "isSingle": false,
                        "isCompilation": false,
                        "isMasteredForItunes": true,
                        "artwork": {
                            "width": 3000,
                            "height": 3000,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/album.jpg/{w}x{h}bb.jpeg"
                        },
                        "playParams": {
                            "id": "1440935467",
                            "kind": "album"
                        }
                    }
                }
            ]
        };
    }

    # Get a Catalog Artist's Relationship View Directly by Name
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + id - The unique identifier for the artist
    # + view - The name of the resource view to fetch
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + with - A list of modifications to apply to the request
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/artists/[string id]/view/["appears-on-albums"|"compilation-albums"|"featured-albums"|"featured-playlists"|"full-albums"|"latest-release"|"live-albums"|"similar-artists"|"singles"|"top-music-videos"|"top-songs" view](string[]? extend, string[]? include, string? l, ("attributes"|"topResults")[]? with, int 'limit = 5) returns AlbumsResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "1584791136",
                    "type": "albums",
                    "href": "/v1/catalog/" + storefront + "/albums/1584791136",
                    "attributes": {
                        "artistName": "Harry Styles",
                        "name": "Harry's House",
                        "releaseDate": "2022-05-20",
                        "genreNames": ["Pop", "Alternative"],
                        "trackCount": 13,
                        "copyright": "© 2022 Harry Styles Limited",
                        "recordLabel": "Columbia Records",
                        "url": "https://music.apple.com/us/album/harrys-house/1584791136",
                        "isComplete": true,
                        "isSingle": false,
                        "isCompilation": false,
                        "isMasteredForItunes": true,
                        "artwork": {
                            "width": 3000,
                            "height": 3000,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/album.jpg/{w}x{h}bb.jpeg"
                        },
                        "playParams": {
                            "id": "1584791136",
                            "kind": "album"
                        }
                    }
                }
            ]
        };
    }

    # Search for Catalog Resources
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + offset - The next page or group of objects to fetch
    # + term - The entered text for the search with `+` characters between each word, to replace spaces (for example `term=james+br`)
    # + types - The list of the types of resources to include in the results
    # + with - A list of modifications to apply to the request
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/search(string? l, string? offset, string term, ("activities"|"albums"|"apple-curators"|"artists"|"curators"|"music-videos"|"playlists"|"record-labels"|"songs"|"stations")[]? types, ("attributes"|"topResults")[]? with, int 'limit = 5) returns SearchResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "results": {
                "albums": {
                    "data": [
                        {
                            "id": "1440935467",
                            "type": "albums",
                            "href": "/v1/catalog/" + storefront + "/albums/1440935467",
                            "attributes": {
                                "artistName": "Adele",
                                "name": "30",
                                "releaseDate": "2021-11-19",
                                "genreNames": ["Pop", "Soul"],
                                "trackCount": 12,
                                "copyright": "© 2021 Melted Stone Ltd.",
                                "recordLabel": "Columbia Records",
                                "url": "https://music.apple.com/us/album/30/1440935467",
                                "isComplete": true,
                                "isSingle": false,
                                "isCompilation": false,
                                "isMasteredForItunes": true,
                                "artwork": {
                                    "width": 3000,
                                    "height": 3000,
                                    "url": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/album.jpg/{w}x{h}bb.jpeg"
                                },
                                "playParams": {
                                    "id": "1440935467",
                                    "kind": "album"
                                }
                            }
                        }
                    ]
                },
                "artists": {
                    "data": [
                        {
                            "id": "262836961",
                            "type": "artists",
                            "href": "/v1/catalog/" + storefront + "/artists/262836961",
                            "attributes": {
                                "name": "Adele",
                                "genreNames": ["Pop", "Soul", "R&B/Soul"],
                                "url": "https://music.apple.com/us/artist/adele/262836961"
                            }
                        }
                    ]
                }
            }
        };
    }

    # Get Multiple Catalog Songs by ID
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + ids - The unique identifiers for the songs
    # + extend - A list of attribute extensions to apply to resources in the response
    # + filter - A filter to apply to the request
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + restrict - A set of restrictions (for example, to restrict explicit content)
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/songs(string[]? ids, string[]? extend, string[]? filter, string[]? include, string? l, string[]? restrict) returns SongsResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "1440936050",
                    "type": "songs",
                    "href": "/v1/catalog/" + storefront + "/songs/1440936050",
                    "attributes": {
                        "albumName": "30",
                        "artistName": "Adele",
                        "name": "Easy On Me",
                        "genreNames": ["Pop", "Soul"],
                        "durationInMillis": 224000,
                        "releaseDate": "2021-10-15",
                        "trackNumber": 1,
                        "discNumber": 1,
                        "hasLyrics": true,
                        "isrc": "GBBKS2100216",
                        "url": "https://music.apple.com/us/song/easy-on-me/1440936050",
                        "artwork": {
                            "width": 3000,
                            "height": 3000,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/song.jpg/{w}x{h}bb.jpeg"
                        },
                        "playParams": {
                            "id": "1440936050",
                            "kind": "song"
                        },
                        "previews": [
                            {
                                "url": "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview116/preview.m4a"
                            }
                        ]
                    }
                }
            ]
        };
    }

    # Get a Catalog Song
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + id - The unique identifier for the song
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/songs/[string id](string[]? extend, string[]? include, string? l) returns SongsResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": id,
                    "type": "songs",
                    "href": "/v1/catalog/" + storefront + "/songs/" + id,
                    "attributes": {
                        "albumName": "Midnights",
                        "artistName": "Taylor Swift",
                        "name": "Anti-Hero",
                        "genreNames": ["Pop", "Alternative"],
                        "durationInMillis": 200000,
                        "releaseDate": "2022-10-21",
                        "trackNumber": 3,
                        "discNumber": 1,
                        "hasLyrics": true,
                        "isrc": "USUG12204275",
                        "url": "https://music.apple.com/us/song/anti-hero/" + id,
                        "contentRating": "clean",
                        "artwork": {
                            "width": 3000,
                            "height": 3000,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/song.jpg/{w}x{h}bb.jpeg"
                        },
                        "playParams": {
                            "id": id,
                            "kind": "song"
                        },
                        "previews": [
                            {
                                "url": "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview122/preview.m4a"
                            }
                        ]
                    }
                }
            ]
        };
    }

    # Get a Catalog Song's Relationship Directly by Name
    #
    # + storefront - An iTunes Store territory, specified by an ISO 3166 alpha-2 country code. The possible values are the id attributes of Storefront objects
    # + id - The unique identifier for the song
    # + relationship - The name of the relationship you want to fetch for this resource
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:InternalServerError (Internal Server Error)
    resource function get catalog/[string storefront]/songs/[string id]/["albums"|"artists"|"composers"|"genres"|"library"|"music-videos"|"station" relationship](string[]? extend, string[]? include, string? l, int 'limit = 5) returns SongsResponse|ErrorsResponseUnauthorized|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "1584791454",
                    "type": "songs",
                    "href": "/v1/catalog/" + storefront + "/songs/1584791454",
                    "attributes": {
                        "albumName": "Harry's House",
                        "artistName": "Harry Styles",
                        "name": "As It Was",
                        "genreNames": ["Pop", "Alternative"],
                        "durationInMillis": 167000,
                        "releaseDate": "2022-04-01",
                        "trackNumber": 1,
                        "discNumber": 1,
                        "hasLyrics": true,
                        "isrc": "USSM12201846",
                        "url": "https://music.apple.com/us/song/as-it-was/1584791454",
                        "artwork": {
                            "width": 3000,
                            "height": 3000,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/song.jpg/{w}x{h}bb.jpeg"
                        },
                        "playParams": {
                            "id": "1584791454",
                            "kind": "song"
                        },
                        "previews": [
                            {
                                "url": "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview122/preview.m4a"
                            }
                        ]
                    }
                }
            ]
        };
    }

    # Get All Library Albums
    #
    # + ids - The unique identifiers for the albums
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + offset - The next page or group of objects to fetch
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:Forbidden (Forbidden)
    # http:InternalServerError (Internal Server Error)
    resource function get me/library/albums(string[]? ids, string[]? extend, string[]? include, string? l, string? offset, int 'limit = 5) returns LibraryAlbumsResponse|ErrorsResponseUnauthorized|ErrorsResponseForbidden|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "i.1234567890",
                    "type": "library-albums",
                    "href": "/v1/me/library/albums/i.1234567890",
                    "attributes": {
                        "artistName": "The Beatles",
                        "name": "Abbey Road",
                        "genreNames": ["Rock", "Pop"],
                        "trackCount": 17,
                        "releaseDate": "1969-09-26",
                        "dateAdded": "2023-01-15",
                        "artwork": {
                            "width": 600,
                            "height": 600,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music/v4/album.jpg/{w}x{h}bb.jpeg"
                        },
                        "playParams": {
                            "id": "i.1234567890",
                            "kind": "album"
                        }
                    }
                },
                {
                    "id": "i.9876543210",
                    "type": "library-albums",
                    "href": "/v1/me/library/albums/i.9876543210",
                    "attributes": {
                        "artistName": "Taylor Swift",
                        "name": "folklore",
                        "genreNames": ["Alternative", "Pop"],
                        "trackCount": 16,
                        "releaseDate": "2020-07-24",
                        "dateAdded": "2023-03-20",
                        "artwork": {
                            "width": 3000,
                            "height": 3000,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/album.jpg/{w}x{h}bb.jpeg"
                        },
                        "playParams": {
                            "id": "i.9876543210",
                            "kind": "album"
                        }
                    }
                }
            ]
        };
    }

    # Get a Library Album
    #
    # + id - The unique identifier for the album
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:Forbidden (Forbidden)
    # http:InternalServerError (Internal Server Error)
    resource function get me/library/albums/[string id](string[]? extend, string[]? include, string? l) returns LibraryAlbumsResponse|ErrorsResponseUnauthorized|ErrorsResponseForbidden|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": id,
                    "type": "library-albums",
                    "href": "/v1/me/library/albums/" + id,
                    "attributes": {
                        "artistName": "Billie Eilish",
                        "name": "Happier Than Ever",
                        "genreNames": ["Alternative", "Pop"],
                        "trackCount": 16,
                        "releaseDate": "2021-07-30",
                        "dateAdded": "2021-08-01",
                        "artwork": {
                            "width": 3000,
                            "height": 3000,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/album.jpg/{w}x{h}bb.jpeg"
                        },
                        "playParams": {
                            "id": id,
                            "kind": "album"
                        }
                    }
                }
            ]
        };
    }

    # Get a Library Album's Relationship Directly by Name
    #
    # + id - The unique identifier for the album
    # + relationship - The name of the relationship you want to fetch for this resource
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:Forbidden (Forbidden)
    # http:InternalServerError (Internal Server Error)
    resource function get me/library/albums/[string id]/["artists"|"genres"|"library"|"record-labels"|"tracks" relationship](string[]? extend, string[]? include, string? l, int 'limit = 5) returns LibraryArtistsResponse|ErrorsResponseUnauthorized|ErrorsResponseForbidden|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "i.artist123",
                    "type": "library-artists",
                    "href": "/v1/me/library/artists/i.artist123",
                    "attributes": {
                        "name": "Billie Eilish"
                    }
                }
            ]
        };
    }

    # Get All Library Artists
    #
    # + ids - The unique identifiers for the artists
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + offset - The next page or group of objects to fetch
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:Forbidden (Forbidden)
    # http:InternalServerError (Internal Server Error)
    resource function get me/library/artists(string[]? ids, string[]? extend, string[]? include, string? l, string? offset, int 'limit = 5) returns LibraryArtistsResponse|ErrorsResponseUnauthorized|ErrorsResponseForbidden|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "i.artist456",
                    "type": "library-artists",
                    "href": "/v1/me/library/artists/i.artist456",
                    "attributes": {
                        "name": "Taylor Swift"
                    }
                },
                {
                    "id": "i.artist789",
                    "type": "library-artists",
                    "href": "/v1/me/library/artists/i.artist789",
                    "attributes": {
                        "name": "The Beatles"
                    }
                }
            ]
        };
    }

    # Get a Library Artist
    #
    # + id - The unique identifier for the artist
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:Forbidden (Forbidden)
    # http:InternalServerError (Internal Server Error)
    resource function get me/library/artists/[string id](string[]? extend, string[]? include, string? l) returns LibraryArtistsResponse|ErrorsResponseUnauthorized|ErrorsResponseForbidden|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": id,
                    "type": "library-artists",
                    "href": "/v1/me/library/artists/" + id,
                    "attributes": {
                        "name": "Ed Sheeran"
                    }
                }
            ]
        };
    }

    # Get a Library Artist's Relationship Directly by Name
    #
    # + id - The unique identifier for the artist
    # + relationship - The name of the relationship you want to fetch for this resource
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:Forbidden (Forbidden)
    # http:InternalServerError (Internal Server Error)
    resource function get me/library/artists/[string id]/["albums"|"genres"|"music-videos"|"playlists"|"station" relationship](string[]? extend, string[]? include, string? l, int 'limit = 5) returns LibraryAlbumsResponse|ErrorsResponseUnauthorized|ErrorsResponseForbidden|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "i.album567",
                    "type": "library-albums",
                    "href": "/v1/me/library/albums/i.album567",
                    "attributes": {
                        "artistName": "Ed Sheeran",
                        "name": "÷ (Divide)",
                        "genreNames": ["Pop", "Singer/Songwriter"],
                        "trackCount": 12,
                        "releaseDate": "2017-03-03",
                        "dateAdded": "2022-06-15",
                        "artwork": {
                            "width": 3000,
                            "height": 3000,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/album.jpg/{w}x{h}bb.jpeg"
                        },
                        "playParams": {
                            "id": "i.album567",
                            "kind": "album"
                        }
                    }
                }
            ]
        };
    }

    # Get All Library Songs
    #
    # + ids - The unique identifiers for the songs
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + offset - The next page or group of objects to fetch
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:Forbidden (Forbidden)
    # http:InternalServerError (Internal Server Error)
    resource function get me/library/songs(string[]? ids, string[]? extend, string[]? include, string? l, string? offset, int 'limit = 5) returns LibrarySongsResponse|ErrorsResponseUnauthorized|ErrorsResponseForbidden|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "i.song123",
                    "type": "library-songs",
                    "href": "/v1/me/library/songs/i.song123",
                    "attributes": {
                        "albumName": "Midnights",
                        "artistName": "Taylor Swift",
                        "name": "Anti-Hero",
                        "genreNames": ["Pop", "Alternative"],
                        "durationInMillis": 200000,
                        "releaseDate": "2022-10-21",
                        "trackNumber": 3,
                        "discNumber": 1,
                        "hasLyrics": true,
                        "contentRating": "clean",
                        "artwork": {
                            "width": 3000,
                            "height": 3000,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/song.jpg/{w}x{h}bb.jpeg"
                        },
                        "playParams": {
                            "id": "i.song123",
                            "kind": "song"
                        }
                    }
                }
            ]
        };
    }

    # Get a Library Song
    #
    # + id - The unique identifier for the song
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:Forbidden (Forbidden)
    # http:InternalServerError (Internal Server Error)
    resource function get me/library/songs/[string id](string[]? extend, string[]? include, string? l) returns LibrarySongsResponse|ErrorsResponseUnauthorized|ErrorsResponseForbidden|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": id,
                    "type": "library-songs",
                    "href": "/v1/me/library/songs/" + id,
                    "attributes": {
                        "albumName": "÷ (Divide)",
                        "artistName": "Ed Sheeran",
                        "name": "Shape of You",
                        "genreNames": ["Pop", "Singer/Songwriter"],
                        "durationInMillis": 233000,
                        "releaseDate": "2017-01-06",
                        "trackNumber": 4,
                        "discNumber": 1,
                        "hasLyrics": true,
                        "artwork": {
                            "width": 3000,
                            "height": 3000,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/song.jpg/{w}x{h}bb.jpeg"
                        },
                        "playParams": {
                            "id": id,
                            "kind": "song"
                        }
                    }
                }
            ]
        };
    }

    # Get a Library Song's Relationship Directly by Name
    #
    # + id - The unique identifier for the song
    # + relationship - The name of the relationship you want to fetch for this resource
    # + extend - A list of attribute extensions to apply to resources in the response
    # + include - Additional relationships to include in the fetch
    # + l - The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    # + 'limit - The number of objects or number of objects in the specified relationship returned
    # + return - returns can be any of following types 
    # http:Ok (OK)
    # http:Unauthorized (Unauthorized)
    # http:Forbidden (Forbidden)
    # http:InternalServerError (Internal Server Error)
    resource function get me/library/songs/[string id]/["albums"|"artists"|"composers"|"genres"|"library"|"music-videos"|"station" relationship](string[]? extend, string[]? include, string? l, int 'limit = 5) returns LibrarySongsResponse|ErrorsResponseUnauthorized|ErrorsResponseForbidden|ErrorsResponseInternalServerError {
        return {
            "data": [
                {
                    "id": "i.song456",
                    "type": "library-songs",
                    "href": "/v1/me/library/songs/i.song456",
                    "attributes": {
                        "albumName": "÷ (Divide)",
                        "artistName": "Ed Sheeran",
                        "name": "Perfect",
                        "genreNames": ["Pop", "Singer/Songwriter"],
                        "durationInMillis": 263000,
                        "releaseDate": "2017-03-03",
                        "trackNumber": 5,
                        "discNumber": 1,
                        "hasLyrics": true,
                        "artwork": {
                            "width": 3000,
                            "height": 3000,
                            "url": "https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/song.jpg/{w}x{h}bb.jpeg"
                        },
                        "playParams": {
                            "id": "i.song456",
                            "kind": "song"
                        }
                    }
                }
            ]
        };
    }

    # Add a Resource to a Library
    #
    # + ids - The unique catalog identifiers for the resources. To indicate the type of resource to be added, ids must be followed by one of the allowed values. Add multiple types in the same request
    # + return - returns can be any of following types 
    # http:Accepted (Accepted)
    # http:Unauthorized (Unauthorized)
    # http:Forbidden (Forbidden)
    # http:InternalServerError (Internal Server Error)
    resource function post me/library(string[] ids) returns http:Accepted|ErrorsResponseUnauthorized|ErrorsResponseForbidden|ErrorsResponseInternalServerError {
        return http:ACCEPTED;
    }
}