// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

# An object that represents artwork
public type Artwork record {
    # The primary text color used if the background color gets displayed
    string textColor1?;
    # The average background color of the image
    string bgColor?;
    # The final post-tertiary text color used if the background color gets displayed
    string textColor4?;
    # The secondary text color used if the background color gets displayed
    string textColor2?;
    # The tertiary text color used if the background color gets displayed
    string textColor3?;
    # The maximum width available for the image
    decimal width?;
    # The URL to request the image asset
    string url?;
    # The maximum height available for the image
    decimal height?;
};

# Collection of errors that occurred during request processing
public type ErrorsResponse record {
    # The collection of errors that occurred while processing the request
    ErrorInformation[] data?;
};

public type GetAlbumsFromCatalogQueriesIdsItemsString string;

# A resource object that represents an album
public type Albums record {
    # The relationships for the album
    record {} relationships?;
    # Information about the request or response. The members may be any of the endpoint parameters
    record {} meta?;
    # The attributes for the album
    AlbumsAttributes attributes?;
    # The identifier for the album
    string id?;
    # The relative location for the album resource
    string href?;
    # This value is always `albums`
    "albums" 'type?;
    # The relationship views for the album
    record {} views?;
};

# Information about an error that occurred while processing a request
public type ErrorInformation record {
    # The code for this error. For possible values, see HTTP Status Codes
    string code?;
    # A long, possibly localized, description of the problem
    string detail?;
    # A unique identifier for this occurrence of the error
    string id?;
    # An object containing references to the source of the error
    ErrorInformationSource 'source?;
    # A short, possibly localized, description of the problem
    string title?;
    # The HTTP status code for this problem
    string status?;
};

public type ErrorsResponseInternalServerError record {|
    *http:InternalServerError;
    ErrorsResponse body;
|};

# The response to an albums request
public type AlbumsResponse record {
    # A relative cursor to fetch the next paginated collection of resources, if more exist
    string next?;
    # The Albums included in the response for the request
    Albums[] data?;
    # Contextual data about the relationship
    record {} meta?;
};

# An object containing references to the source of the error
public type ErrorInformationSource record {
    # A pointer to the associated entry in the request document
    string pointer?;
    # The URI query parameter that caused the error
    string 'parameter?;
};

# An object that represents play parameters for resources
public type PlayParameters record {
    # The kind of the content to use for playback
    string kind?;
    # The ID of the content to use for playback
    string id?;
};

# The attributes for the album
public type AlbumsAttributes record {
    # The copyright text
    string copyright?;
    # The names of the genres associated with this album
    string[] genreNames?;
    # The release date of the album, when known, in `YYYY-MM-DD` or `YYYY` format. Pre-release content may have an expected release date in the future
    string releaseDate?;
    # Indicates whether the response delivered the album as an Apple Digital Master
    boolean isMasteredForItunes?;
    # The Universal Product Code for the album
    string upc?;
    # An object that represents artwork
    Artwork artwork?;
    # An object that represents play parameters for resources
    PlayParameters playParams?;
    # The URL for sharing the album in Apple Music
    string url?;
    # The name of the record label for the album
    string recordLabel?;
    # Indicates if the album is marked as a compilation. If `true`, the album is a compilation; otherwise, it is not
    boolean isCompilation?;
    # The number of tracks
    decimal trackCount?;
    # The url of the artist for this content
    string artistUrl?;
    # Indicates whether the album contains a single song
    boolean isSingle?;
    # The localized name of the album
    string name?;
    # The name of the primary artist associated with the album
    string artistName?;
    # The Recording Industry Association of America (RIAA) rating of the content. The possible values for this rating are clean and explicit. No value means no rating
    "clean"|"explicit" contentRating?;
    # An object that represents a notes attribute
    EditorialNotes editorialNotes?;
    # Indicates whether the album is complete. If `true`, the album is complete; otherwise, it is not. An album is complete if it contains all its tracks and songs
    boolean isComplete?;
};

# Represents the Queries record for the operation: getAlbumsFromCatalog
public type GetAlbumsFromCatalogQueries record {
    # A list of attribute extensions to apply to resources in the response
    string[] extend?;
    # A filter to apply to the request
    string[] filter?;
    # Additional relationships to include in the fetch
    string[] include?;
    # The unique identifiers for the albums
    GetAlbumsFromCatalogQueriesIdsItemsString[] ids?;
    # The localization to use, specified by a language tag. The possible values are in the `supportedLanguageTags` array belonging to the `Storefront` object specified by `storefront`. Otherwise, the default is `defaultLanguageTag` in `Storefront`
    string l?;
    # A set of restrictions (for example, to restrict explicit content)
    string[] restrict?;
};

public type ErrorsResponseUnauthorized record {|
    *http:Unauthorized;
    ErrorsResponse body;
|};

# An object that represents a notes attribute
public type EditorialNotes record {
    # Notes shown when the content is prominently displayed
    string standard?;
    # Name for the editorial notes
    string name?;
    # Abbreviated notes shown inline or when the content appears alongside other content
    string short?;
    # The tag line for the editorial notes
    string tagline?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};
